/**
 * Reads shared SQL templates from protocol/sql/{postgres,mysql}/ and generates
 * language-specific constant modules for each SDK.
 *
 * Usage:
 *   npx tsx protocol/sql/codegen.ts           # generate all
 *   npx tsx protocol/sql/codegen.ts --check   # verify generated files are up to date
 */

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'fs'
import { join, resolve } from 'path'

const SQL_DIR = resolve(__dirname)
const ROOT = resolve(SQL_DIR, '../..')
const DIALECTS = ['postgres', 'mysql'] as const

type QueryMap = Record<string, Record<string, string>>

function loadQueries(): QueryMap {
  const queries: QueryMap = {}
  for (const dialect of DIALECTS) {
    queries[dialect] = {}
    const dir = join(SQL_DIR, dialect)
    for (const file of readdirSync(dir).filter((f) => f.endsWith('.sql')).sort()) {
      const name = file.replace('.sql', '')
      queries[dialect][name] = readFileSync(join(dir, file), 'utf-8').trimEnd()
    }
  }
  return queries
}

function constName(dialect: string, query: string): string {
  return `${dialect.toUpperCase()}_${query.toUpperCase()}`
}

function snakeName(dialect: string, query: string): string {
  return `${dialect}_${query}`.toUpperCase()
}

// ---------------------------------------------------------------------------
// TypeScript
// ---------------------------------------------------------------------------

function generateTypeScript(queries: QueryMap): string {
  const lines = [
    '// AUTO-GENERATED by protocol/sql/codegen.ts — do not edit',
    '',
  ]
  for (const dialect of DIALECTS) {
    for (const [name, sql] of Object.entries(queries[dialect])) {
      lines.push(`export const ${constName(dialect, name)} = \`${sql}\``)
      lines.push('')
    }
  }
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Python
// ---------------------------------------------------------------------------

function generatePython(queries: QueryMap): string {
  const lines = [
    '# AUTO-GENERATED by protocol/sql/codegen.ts — do not edit',
    '',
  ]
  for (const dialect of DIALECTS) {
    for (const [name, sql] of Object.entries(queries[dialect])) {
      lines.push(`${snakeName(dialect, name)} = """\\`)
      lines.push(`${sql}"""`)
      lines.push('')
    }
  }
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Elixir
// ---------------------------------------------------------------------------

function generateElixir(queries: QueryMap): string {
  const lines = [
    '# AUTO-GENERATED by protocol/sql/codegen.ts — do not edit',
    'defmodule Autonoma.Generated.SQLQueries do',
    '  @moduledoc false',
    '',
  ]
  for (const dialect of DIALECTS) {
    for (const [name, sql] of Object.entries(queries[dialect])) {
      const fnName = `${dialect}_${name}`
      lines.push(`  def ${fnName} do`)
      lines.push(`    """`)
      lines.push(`    ${sql.split('\n').join('\n    ')}`)
      lines.push(`    """`)
      lines.push(`  end`)
      lines.push('')
    }
  }
  lines.push('end')
  lines.push('')
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Go
// ---------------------------------------------------------------------------

function generateGo(queries: QueryMap): string {
  const lines = [
    '// AUTO-GENERATED by protocol/sql/codegen.ts — do not edit',
    '',
    'package autonoma',
    '',
  ]
  for (const dialect of DIALECTS) {
    for (const [name, sql] of Object.entries(queries[dialect])) {
      lines.push(`const ${constName(dialect, name)} = \`${sql}\``)
      lines.push('')
    }
  }
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const targets = [
  {
    path: join(ROOT, 'sdks/typescript/packages/sdk/src/generated/sql-queries.ts'),
    generate: generateTypeScript,
  },
  {
    path: join(ROOT, 'sdks/python/src/autonoma/generated/sql_queries.py'),
    generate: generatePython,
  },
  {
    path: join(ROOT, 'sdks/elixir/lib/autonoma/generated/sql_queries.ex'),
    generate: generateElixir,
  },
  {
    path: join(ROOT, 'sdks/go/autonoma/sql_queries.go'),
    generate: generateGo,
  },
]

const queries = loadQueries()
const check = process.argv.includes('--check')
let dirty = false

for (const target of targets) {
  const content = target.generate(queries)

  if (check) {
    if (!existsSync(target.path)) {
      console.error(`MISSING: ${target.path}`)
      dirty = true
      continue
    }
    const existing = readFileSync(target.path, 'utf-8')
    if (existing !== content) {
      console.error(`OUT OF DATE: ${target.path}`)
      dirty = true
    }
  } else {
    // Ensure parent directory exists
    const dir = target.path.substring(0, target.path.lastIndexOf('/'))
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true })
    }
    writeFileSync(target.path, content)
    console.log(`Generated: ${target.path}`)
  }
}

if (check && dirty) {
  console.error('\nRun `npx tsx protocol/sql/codegen.ts` to regenerate.')
  process.exit(1)
}
